/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author noelb
 */
public class VentanaPrincipal extends javax.swing.JFrame {
private GUI.PanelArbol dibujadorArbol;
private controladores.SimuladorSO simulador;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    this.setLocationRelativeTo(null);
    simulador = new controladores.SimuladorSO();

    // --- CÓDIGO NUEVO PARA EL ÁRBOL ---
    dibujadorArbol = new GUI.PanelArbol(simulador.getColaImpresion());
    panelArbol.setLayout(new java.awt.BorderLayout());
    panelArbol.add(dibujadorArbol, java.awt.BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCargarCSV = new javax.swing.JButton();
        txtIdUsuario = new javax.swing.JTextField();
        cbxTipoUsuario = new javax.swing.JComboBox<>();
        btnAgregarUsuario = new javax.swing.JButton();
        btnEliminarUsuario = new javax.swing.JButton();
        txtNombreDoc = new javax.swing.JTextField();
        chkPrioridad = new javax.swing.JCheckBox();
        btnEnviarImpresion = new javax.swing.JButton();
        btnCancelarImpresion = new javax.swing.JButton();
        btnLiberarImpresora = new javax.swing.JButton();
        txtTamanoDoc = new javax.swing.JTextField();
        txtTipoDoc = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaUsuarios = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaCola = new javax.swing.JTextArea();
        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollBar2 = new javax.swing.JScrollBar();
        panelArbol = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulador de Cola de Impresión - SO");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnCargarCSV.setText("Cargar Archivo CSV");
        btnCargarCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarCSVActionPerformed(evt);
            }
        });

        txtIdUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtIdUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdUsuarioActionPerformed(evt);
            }
        });

        cbxTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "prioridad_alta", "prioridad_media", "prioridad_baja" }));

        btnAgregarUsuario.setText("Agregar Usuario");
        btnAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarUsuarioActionPerformed(evt);
            }
        });

        btnEliminarUsuario.setText("Eliminar Usuario");
        btnEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarUsuarioActionPerformed(evt);
            }
        });

        txtNombreDoc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        chkPrioridad.setText("Marcar como prioritario");

        btnEnviarImpresion.setText("Enviar a Imprimir");
        btnEnviarImpresion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarImpresionActionPerformed(evt);
            }
        });

        btnCancelarImpresion.setText("Cancelar Documento");
        btnCancelarImpresion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarImpresionActionPerformed(evt);
            }
        });

        btnLiberarImpresora.setText("Imprimir Siguiente / Liberar");
        btnLiberarImpresora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLiberarImpresoraActionPerformed(evt);
            }
        });

        txtTamanoDoc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtTipoDoc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTipoDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoDocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCargarCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(btnEnviarImpresion))
                            .addComponent(btnCancelarImpresion))
                        .addContainerGap(66, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chkPrioridad)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnAgregarUsuario)
                        .addComponent(btnEliminarUsuario)))
                .addGap(59, 59, 59))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTamanoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnLiberarImpresora)
                        .addGap(45, 45, 45))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnCargarCSV)
                .addGap(28, 28, 28)
                .addComponent(txtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAgregarUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminarUsuario)
                .addGap(18, 18, 18)
                .addComponent(txtNombreDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTamanoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkPrioridad)
                .addGap(18, 18, 18)
                .addComponent(btnEnviarImpresion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelarImpresion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLiberarImpresora)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtAreaUsuarios.setColumns(20);
        txtAreaUsuarios.setRows(5);
        jScrollPane1.setViewportView(txtAreaUsuarios);

        txtAreaCola.setColumns(20);
        txtAreaCola.setRows(5);
        jScrollPane2.setViewportView(txtAreaCola);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        panelArbol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelArbolLayout = new javax.swing.GroupLayout(panelArbol);
        panelArbol.setLayout(panelArbolLayout);
        panelArbolLayout.setHorizontalGroup(
            panelArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 248, Short.MAX_VALUE)
        );
        panelArbolLayout.setVerticalGroup(
            panelArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelArbol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelArbol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarCSVActionPerformed
  {                                             
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setDialogTitle("Seleccionar archivo de usuarios CSV");
        
        javax.swing.filechooser.FileNameExtensionFilter filtro = new javax.swing.filechooser.FileNameExtensionFilter("Archivos CSV", "csv");
        fileChooser.setFileFilter(filtro);
        
        int seleccion = fileChooser.showOpenDialog(this);
        
        if (seleccion == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File archivo = fileChooser.getSelectedFile();
            String ruta = archivo.getAbsolutePath();
            
            boolean exito = simulador.cargarUsuariosDesdeCSV(ruta);
            
            if (exito) {
                javax.swing.JOptionPane.showMessageDialog(this, "Usuarios cargados correctamente.", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                actualizarVistas(); 
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar el archivo.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    }//GEN-LAST:event_btnCargarCSVActionPerformed

    private void txtIdUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdUsuarioActionPerformed

    private void btnAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarUsuarioActionPerformed
String idUsuario = txtIdUsuario.getText().trim();
        String tipoUsuario = cbxTipoUsuario.getSelectedItem().toString();

        if (idUsuario.isEmpty()) {
            // Cumpliendo rúbrica: Alerta de error
            javax.swing.JOptionPane.showMessageDialog(this, "El ID de usuario no puede estar vacío.", "Error de validación", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (simulador.buscarUsuario(idUsuario) != null) {
            javax.swing.JOptionPane.showMessageDialog(this, "El usuario ya existe en el sistema.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        simulador.agregarUsuario(idUsuario, tipoUsuario);
        javax.swing.JOptionPane.showMessageDialog(this, "Usuario agregado con éxito.");
        txtIdUsuario.setText(""); // Limpiar campo
        actualizarVistas();
    }//GEN-LAST:event_btnAgregarUsuarioActionPerformed

    private void btnEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUsuarioActionPerformed
String idUsuario = txtIdUsuario.getText().trim();

        if (idUsuario.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese el ID del usuario a eliminar.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        boolean eliminado = simulador.eliminarUsuario(idUsuario);
        if (eliminado) {
            javax.swing.JOptionPane.showMessageDialog(this, "Usuario eliminado correctamente.");
            txtIdUsuario.setText("");
            actualizarVistas();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontró un usuario con ese ID.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarUsuarioActionPerformed

    private void btnEnviarImpresionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarImpresionActionPerformed
String idUsuario = txtIdUsuario.getText().trim();
        String nombreDoc = txtNombreDoc.getText().trim();
        String tamanoStr = txtTamanoDoc.getText().trim();
        // Nota: Asume que agregaste un campo txtTipoDoc, si no lo tienes, pon un texto fijo como "PDF"
        String tipoDoc = txtTipoDoc.getText().trim(); 
        boolean esPrioritario = chkPrioridad.isSelected();

        // Validaciones de seguridad (Rúbrica de Usabilidad)
        if (idUsuario.isEmpty() || nombreDoc.isEmpty() || tamanoStr.isEmpty() || tipoDoc.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor llene todos los campos del documento y el ID del usuario.", "Campos incompletos", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int tamano = Integer.parseInt(tamanoStr);
            if (tamano <= 0) throw new NumberFormatException();

            modelos.Usuario u = simulador.buscarUsuario(idUsuario);
            if (u != null) {
                // Creamos el documento, lo agregamos al usuario y lo mandamos a la cola
                modelos.Documento doc = new modelos.Documento(nombreDoc, tamano, tipoDoc, esPrioritario);
                u.agregarDocumento(doc); 
                simulador.enviarAImpresion(idUsuario, doc);
                
                simulador.tickReloj(); // El tiempo del sistema avanza
                
                javax.swing.JOptionPane.showMessageDialog(this, "Documento encolado correctamente.");
                
                // Limpiar campos
                txtNombreDoc.setText("");
                txtTamanoDoc.setText("");
                txtTipoDoc.setText("");
                chkPrioridad.setSelected(false);
                
                actualizarVistas();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "El usuario ingresado no existe. Regístrelo primero.", "Usuario no encontrado", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "El tamaño del documento debe ser un número entero mayor a 0.", "Dato inválido", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEnviarImpresionActionPerformed

    private void btnCancelarImpresionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarImpresionActionPerformed
String idUsuario = txtIdUsuario.getText().trim();
        String nombreDoc = txtNombreDoc.getText().trim();

        if (idUsuario.isEmpty() || nombreDoc.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Para cancelar, ingrese el ID del usuario y el Nombre del documento.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        boolean cancelado = simulador.cancelarImpresion(idUsuario, nombreDoc);
        if (cancelado) {
            javax.swing.JOptionPane.showMessageDialog(this, "El documento fue cancelado y retirado de la cola exitosamente.");
            simulador.tickReloj(); // El tiempo avanza
            actualizarVistas();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontró el documento en la cola. Asegúrese de que el nombre y el usuario sean correctos.", "Error al cancelar", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCancelarImpresionActionPerformed

    private void btnLiberarImpresoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiberarImpresoraActionPerformed
modelos.RegistroImpresion impreso = simulador.liberarImpresora();
        
        if (impreso != null) {
            String msj = "Se ha impreso exitosamente:\n" + 
                         "Documento: " + impreso.getDocumento().getNombre() + "." + impreso.getDocumento().getTipo() + "\n" +
                         "Tamaño: " + impreso.getDocumento().getTamano() + " páginas.";
            
            javax.swing.JOptionPane.showMessageDialog(this, msj, "Impresión Completada", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            simulador.tickReloj(); // El tiempo avanza por imprimir
            actualizarVistas();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "La cola de impresión está vacía. No hay nada que imprimir.", "Aviso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnLiberarImpresoraActionPerformed

    private void txtTipoDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoDocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
        }
        /**
     * Método auxiliar para refrescar la interfaz gráfica con los datos actuales.
     */
    private void actualizarVistas() {
        // 1. Actualizar el JTextArea de Usuarios (txtAreaUsuarios)
        StringBuilder sbUsuarios = new StringBuilder();
        sbUsuarios.append("--- USUARIOS REGISTRADOS ---\n");
        for (int i = 0; i < simulador.getCantidadUsuarios(); i++) {
            sbUsuarios.append(simulador.getUsuarios()[i].toString()).append("\n");
        }
        txtAreaUsuarios.setText(sbUsuarios.toString());

        // 2. Actualizar el JTextArea de la Cola de Impresión (txtAreaCola)
        StringBuilder sbCola = new StringBuilder();
        sbCola.append("--- COLA DE IMPRESIÓN (Montículo) ---\n");
        modelos.RegistroImpresion[] arreglo = simulador.getColaImpresion().getArreglo();
        for (int i = 0; i < simulador.getColaImpresion().getTamanoActual(); i++) {
            sbCola.append(arreglo[i].toString()).append("\n");
        }
        txtAreaCola.setText(sbCola.toString());
        dibujadorArbol.repaint();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarUsuario;
    private javax.swing.JButton btnCancelarImpresion;
    private javax.swing.JButton btnCargarCSV;
    private javax.swing.JButton btnEliminarUsuario;
    private javax.swing.JButton btnEnviarImpresion;
    private javax.swing.JButton btnLiberarImpresora;
    private javax.swing.JComboBox<String> cbxTipoUsuario;
    private javax.swing.JCheckBox chkPrioridad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollBar jScrollBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelArbol;
    private javax.swing.JTextArea txtAreaCola;
    private javax.swing.JTextArea txtAreaUsuarios;
    private javax.swing.JTextField txtIdUsuario;
    private javax.swing.JTextField txtNombreDoc;
    private javax.swing.JTextField txtTamanoDoc;
    private javax.swing.JTextField txtTipoDoc;
    // End of variables declaration//GEN-END:variables

}
